# version: 2.1
# orbs:
#   cypress: cypress-io/cypress@1
# workflows:
#   build:
#     jobs:
#       - cypress/install
#       - cypress/run:
#           requires:
#             - cypress/install
#           parallel: true
#           parallelism: 4
         
version: 2.1
workflows:
  testing:
    jobs:
      - runner-test
jobs:
  runner-test:
    machine: true
    resource_class: bogdanstt/cy_tests
    steps:
      - run: echo "Hi I'm on Runners!"